# Generated by Django 5.2.4 on 2025-08-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="qualification_type",
            field=models.CharField(
                choices=[("UG", "Undergraduate"), ("PG", "Postgraduate")],
                default="UG",
                help_text="Qualification level of the module",
                max_length=2,
            ),
        ),
    ]
