# Generated by Django 5.2.4 on 2025-08-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0002_module_qualification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="ModeOfDelivery",
            field=models.CharField(
                choices=[("Online", "Onine"), ("On Campus", "On Campus")],
                default="On Campus",
                help_text="mode of Delivery",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="ModeOfStudy",
            field=models.CharField(
                choices=[("Part time", "Part time"), ("Full time", "Full time")],
                default="Full time",
                help_text="mode of study",
                max_length=10,
            ),
        ),
    ]
