# Generated by Django 5.2.4 on 2025-08-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0003_module_modeofdelivery_module_modeofstudy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="module",
            old_name="ModeOfDelivery",
            new_name="modeOfDelivery",
        ),
        migrations.RenameField(
            model_name="module",
            old_name="ModeOfStudy",
            new_name="modeOfStudy",
        ),
    ]
