# Generated by Django 5.2.4 on 2025-08-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0005_courseprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="credits",
            field=models.IntegerField(default=15),
        ),
    ]
