# Generated by Django 5.2.4 on 2025-08-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0006_module_credits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="modeOfDelivery",
        ),
        migrations.RemoveField(
            model_name="module",
            name="modeOfStudy",
        ),
        migrations.AddField(
            model_name="module",
            name="mode_of_delivery",
            field=models.CharField(
                choices=[("Online", "Online"), ("On Campus", "On Campus")],
                default="On Campus",
                help_text="Mode of delivery",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="mode_of_study",
            field=models.CharField(
                choices=[("Part time", "Part time"), ("Full time", "Full time")],
                default="Full time",
                help_text="Mode of study",
                max_length=10,
            ),
        ),
    ]
